language: node_js

node_js:
  - '14'
  - '12'
  - '10'
  - '8'
  - 'node'
  - 'lts/*'

before_script:
  - npm install

script:
  - npm run lint
  - npm run test

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - main
